export const graphData = {
  nodes: [
    { id: 'AI', group: 1, val: 10 },
    { id: 'Machine Learning', group: 1, val: 8 },
    { id: 'Deep Learning', group: 1, val: 6 },
    { id: 'Neural Networks', group: 1, val: 6 },
    { id: 'Programming', group: 2, val: 8 },
    { id: 'Python', group: 2, val: 6 },
    { id: 'JavaScript', group: 2, val: 6 },
    { id: 'React', group: 2, val: 4 },
    { id: 'Design', group: 3, val: 8 },
    { id: 'UI/UX', group: 3, val: 6 },
    { id: 'Figma', group: 3, val: 4 },
    { id: 'Cloud Computing', group: 4, val: 8 },
    { id: 'Cloudflare', group: 4, val: 6 },
    { id: 'Serverless', group: 4, val: 4 },
  ],
  links: [
    { source: 'AI', target: 'Machine Learning' },
    { source: 'Machine Learning', target: 'Deep Learning' },
    { source: 'Deep Learning', target: 'Neural Networks' },
    { source: 'AI', target: 'Programming' },
    { source: 'Programming', target: 'Python' },
    { source: 'Programming', target: 'JavaScript' },
    { source: 'JavaScript', target: 'React' },
    { source: 'Machine Learning', target: 'Python' },
    { source: 'Design', target: 'UI/UX' },
    { source: 'UI/UX', target: 'Figma' },
    { source: 'React', target: 'UI/UX' },
    { source: 'Cloud Computing', target: 'Serverless' },
    { source: 'Cloud Computing', target: 'Cloudflare' },
    { source: 'Serverless', target: 'Cloudflare' },
    { source: 'Programming', target: 'Cloud Computing' },
  ],
};
export const cortexContent = [
  {
    id: '1',
    title: 'Intro to Neural Networks',
    type: 'article',
    status: 'published',
    createdAt: new Date('2023-10-26'),
    keywords: ['AI', 'Deep Learning', 'Guide'],
  },
  {
    id: '2',
    title: 'Cloudflare Workers Architecture',
    type: 'guide',
    status: 'published',
    createdAt: new Date('2023-11-15'),
    keywords: ['Cloudflare', 'Serverless', 'Architecture'],
  },
  {
    id: '3',
    title: 'UX Research Methods',
    type: 'template',
    status: 'draft',
    createdAt: new Date('2024-01-05'),
    keywords: ['UX', 'Research', 'Design'],
  },
  {
    id: '4',
    title: 'React State Management Snippet',
    type: 'code',
    status: 'published',
    createdAt: new Date('2023-09-01'),
    keywords: ['React', 'JavaScript', 'Zustand'],
  },
  {
    id: '5',
    title: 'AI Project Ideas',
    type: 'collection',
    status: 'draft',
    createdAt: new Date('2024-02-20'),
    keywords: ['AI', 'Ideas', 'Collection'],
  },
];